version: '3.3'

services:
  backend:
    image: filipton/fkm-backend:latest
    container_name: backend
    network_mode: host
    build: ./backend
    volumes:
      - /run/dbus:/run/dbus:ro
      - ./build:/app/firmware
    environment:
      - PORT=8080
      - FIRMWARE_DIR=/app/firmware
      - API_URL=http://localhost:5001
      - API_TOKEN=paste_your_token_here
      - RUST_LOG=none,backend=debug
    restart: unless-stopped

# NOTE: replace this with actual api
  api:
    container_name: api
    build: ./backend/test-api
    ports:
      - 5001:5000
    restart: unless-stopped
