version: '3.3'

services:
  backend:
    image: filipton/fkm-backend:latest
    build: ./backend
    volumes:
      - ./proj/build:/app/firmware
    environment:
      - PORT=8080
      - FIRMWARE_DIR=./firmware
      - API_URL=http://localhost:5000
    network_mode: host

# NOTE: replace this with actual api
  api:
    container_name: api
    image: filipton/fkm-api
    build: ./backend/test-api
    ports:
      - 5000:5000
