version: '3.3'

services:
  backend:
    image: filipton/fkm-backend:latest
    container_name: backend
    network_mode: host
    build: ./backend
    volumes:
      - ./proj/build:/app/firmware
    environment:
      - PORT=8080
      - FIRMWARE_DIR=./firmware
      - API_URL=http://localhost:5001
      - RUST_LOG=none,backend=trace
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1

# NOTE: replace this with actual api
  api:
    container_name: api
    build: ./backend/test-api
    ports:
      - 5001:5000
    restart: unless-stopped
