version: '3.3'

services:
  backend:
    network_mode: host
    image: filipton/fkm-backend:latest
    build: ./backend
    volumes:
      - ./proj/build:/app/firmware
    environment:
      - PORT=8080
      - FIRMWARE_DIR=./firmware
      - API_URL=http://api:5000

# NOTE: replace this with actual api
  api:
    image: filipton/fkm-api
    build: ./backend/test-api
    ports:
      - 5000:5000
