version: '3.3'

services:
  bind9:
    image: filipton/fkm-dns:latest
    container_name: dns
    build: ./dns
    environment:
      - BIND9_USER=root
      - TZ=Europe/Warsaw
      - SERVER_IP=127.0.0.1
    ports: 
      - "53:53"
      - "53:53/udp"
    restart: unless-stopped

  backend:
    image: filipton/fkm-backend:latest
    container_name: backend
    network_mode: host
    build: ./backend
    volumes:
      - ./proj/build:/app/firmware
    environment:
      - PORT=8080
      - FIRMWARE_DIR=./firmware
      - API_URL=http://localhost:5000
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1

# NOTE: replace this with actual api
  api:
    image: filipton/fkm-api
    container_name: api
    build: ./backend/test-api
    ports:
      - 5000:5000
    restart: unless-stopped
