[alias]
esp32 = "run --no-default-features --features=esp32 --target=xtensa-esp32-none-elf"
esp32c3 = "run --no-default-features --features=esp32c3 --target=riscv32imc-unknown-none-elf"

#[target.riscv32imc-unknown-none-elf]
#runner = "espflash flash --monitor -T ./partitions.csv --erase-parts otadata"

target = "riscv32imc-unknown-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor -T ./partitions.csv --erase-parts otadata"
rustflags = [
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor -T ./partitions.csv --erase-parts otadata"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[env]
ESP_LOG="INFO"

[unstable]
build-std = ["alloc", "core"]
