[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor --partition-table ./partitions.csv --erase-parts otadata"
rustflags = [
  "-C", "force-frame-pointers",
]

[build]
target = "riscv32imc-unknown-none-elf"

[env]
ESP_LOG="INFO"

[unstable]
build-std = ["alloc", "core"]
