[alias]
esp32 = "run --no-default-features --features=esp32 --target=xtensa-esp32-none-elf"

target = "riscv32imc-unknown-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor -T ./partitions.csv --erase-parts otadata"
rustflags = [
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
#runner    = "espflash flash --monitor -T ./partitions.csv --erase-parts otadata"
runner    = "/home/pilif/projects/pico-esp-bridge/serial-test/flash.sh -T ./partitions.csv --erase-parts otadata --baud 3000000"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[build]
target = "riscv32imc-unknown-none-elf"

[env]
ESP_LOG="INFO"

[unstable]
build-std = ["alloc", "core"]
