name: PlatformIO CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - firmware/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ./firmware/.pio
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Build PlatformIO Project
        run: bash ./build.sh
        working-directory: ./firmware

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./build
